# Generated by Django 4.2.7 on 2023-12-22 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_info", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="姓名",
            ),
        ),
    ]
