# Generated by Django 4.2.7 on 2023-12-22 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_info", "0004_alter_teacher_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="姓名",
            ),
        ),
    ]
