# Generated by Django 4.2.7 on 2023-12-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_info", "0005_alter_student_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
