# Generated by Django 4.2.7 on 2023-12-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_info", "0009_alter_student_dept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="dept",
            field=models.CharField(max_length=50, verbose_name="学院名称"),
        ),
    ]
