# Generated by Django 4.2.7 on 2023-12-27 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_info", "0010_alter_teacher_dept"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dept",
        ),
    ]
