# Generated by Django 4.2.7 on 2023-12-27 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_info", "0011_delete_dept"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="课程编号",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="课程名称")),
                (
                    "year",
                    models.PositiveSmallIntegerField(default=2023, verbose_name="学年"),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("Spring", "春季"),
                            ("Summer", "夏季"),
                            ("Fall", "秋季"),
                            ("Winter", "冬季"),
                        ],
                        max_length=10,
                        verbose_name="学期",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(to="user_info.student", verbose_name="选课学生"),
                ),
                (
                    "teachers",
                    models.ManyToManyField(to="user_info.teacher", verbose_name="授课教师"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="资料编号"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="资料标题")),
                ("content", models.TextField(blank=True, verbose_name="内容")),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="course.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(to="user_info.student", verbose_name="已读学生"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_info.teacher",
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_time"],
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        unique=True, upload_to="uploads", verbose_name="路径"
                    ),
                ),
                ("file_name", models.TextField(blank=True, verbose_name="文件名")),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="生成时间"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="course.material",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_time"],
            },
        ),
    ]
