# Generated by Django 4.2.7 on 2023-12-27 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user_info", "0011_delete_dept"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="course.material",
                verbose_name="课程材料",
            ),
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="作业编号"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="资料标题")),
                (
                    "submit_begin_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始提交时间"
                    ),
                ),
                ("submit_end_time", models.DateTimeField(verbose_name="提交截止时间")),
                (
                    "view_begin_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始可见时间"
                    ),
                ),
                ("view_end_time", models.DateTimeField(verbose_name="最后可见时间")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="course.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_info.teacher",
                        verbose_name="布置者",
                    ),
                ),
            ],
            options={
                "ordering": ["-submit_end_time"],
            },
        ),
    ]
