# Generated by Django 4.2.7 on 2023-12-26 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user_info", "0008_remove_dept_id_alter_dept_name"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="资料编号"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="资料标题")),
                ("content", models.TextField(blank=True, verbose_name="内容")),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="course.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(to="user_info.student", verbose_name="已读学生"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_info.teacher",
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_time"],
                "unique_together": {("course", "title")},
            },
        ),
    ]
