# Generated by Django 4.2.7 on 2023-12-26 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_material"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="material",
            unique_together=set(),
        ),
    ]
