# Generated by Django 4.2.7 on 2023-12-26 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_alter_material_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        unique=True, upload_to="uploads", verbose_name="路径"
                    ),
                ),
                ("file_name", models.TextField(blank=True, verbose_name="文件名")),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="生成时间"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="course.material",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_time"],
            },
        ),
    ]
