# Generated by Django 4.2.7 on 2023-12-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_problem_choice_submission_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="answer",
            name="score",
        ),
        migrations.AlterField(
            model_name="answer",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="course.problem",
                verbose_name="问题",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="course.submission",
                verbose_name="提交",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="course.homework",
                verbose_name="作业",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="remark",
            field=models.TextField(default="", verbose_name="评语"),
        ),
    ]
